# Generated by Django 3.1.5 on 2021-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='GitHub',
            field=models.URLField(blank=True),
        ),
    ]
