# Generated by Django 3.1.5 on 2021-01-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Summary',
            field=models.CharField(max_length=1000),
        ),
    ]
